#!/bin/bash

export PHPSWITCH_FILE=`which php$1`;

if [ -z $PHPSWITCH_FILE ]; then
	echo 'Not found version of PHP ('$1')';
	echo 'Command: "which php'$1'" return empty';
	exit 1;
fi

echo 'Switch PHP version To ('$1'):';
printenv PHPSWITCH_FILE;

unlink /etc/alternatives/php;

cd /etc/alternatives;
ln -s $PHPSWITCH_FILE php