#!/bin/bash

if [ $1 == "-v" ]; then
	echo "";
	echo "     Usage:";
	echo "     $ phpswitch <version>";
	echo "";
	echo "     Example:";
	echo "     $ phpswitch 7.2";
	echo "";
	exit 0;
fi

export PHPSWITCH_FILE=`which php$1`;

if [ -z $PHPSWITCH_FILE ]; then
	echo 'Not found version of PHP ('$1')';
	echo 'Command: "which php'$1'" return empty';
	exit 1;
fi

echo 'Switch PHP version To ('$1'):';
printenv PHPSWITCH_FILE;

sudo unlink /etc/alternatives/php;

cd /etc/alternatives;
sudo ln -s $PHPSWITCH_FILE php